spring.profiles.active: @profiles.active@
server:
  display-name: Admin
  address: 0.0.0.0
  context-path: /${virtual.directory}
  compression.min-response-size: 1024
  compression.enabled: true
  compression.mime-types: application/xhtml+xml,application/json,application/xml,text/html,text/xml,text/plain,text/css,application/x-javascript,text/javascript,image/jpeg,image/gif,image/png
  tomcat.uri-encoding: UTF-8
  tomcat.remote_ip_header: X-Forwarded-For
  tomcat.protocol_header: X-Forwarded-Proto
  use-forward-headers: true
spring:
  application:
    name: chinapopin-cdwhz-web
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  http:
    encoding.charset: UTF-8
    encoding.enable: true
    encoding.force: true
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  jersey:
    application-path: /api
  redis:
      pool.max-active: 30
      pool.max-idle: 15
      pool.max-wait: 10000
      pool.min-idle: 5
      timeout: 12000
      ssl: false
security:
  oauth2.resource.filter-order: 3
  headers.frame: false
endpoints:
  enabled: false
  info:
    enabled: true
  health:
    enabled: true
  metrics:
    enabled: true
management:
  security:
    enabled: false
logging:
  #config: classpath:log4j2.xml